sudo: required
services:
    - docker

before_install:
    - docker build -t parul5sahoo/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true parul5sahoo/react-test npm test

after_success:
    - docker build -t parul5sahoo/multi-client ./client
    - docker build -t parul5sahoo/multi-nginx ./nginx
    - docker build -t parul5sahoo/multi-server ./server
    - docker build -t parul5sahoo/multi-worker ./worker

    ## login to docker-CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    ## push above built images to docker hub
    - docker push parul5sahoo/multi-client
    - docker push parul5sahoo/multi-nginx
    - docker push parul5sahoo/multi-server
    - docker push parul5sahoo/multi-worker